# Generated by Django 4.2.16 on 2024-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(default='F', max_length=1)),
                ('cBirthday', models.DateField()),
                ('cEmail', models.CharField(max_length=100)),
                ('cPhone', models.CharField(max_length=20)),
                ('cAddr', models.CharField(max_length=255)),
                ('cHeight', models.IntegerField(blank=True, null=True)),
                ('cWeight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
